import io
import pandas as pd
from fpdf import FPDF
from datetime import datetime
import visualization
import data_loader

class AnalysisReport(FPDF):
    def header(self):
        # Branding
        self.set_fill_color(251, 113, 133) # Magenta theme highlight
        self.rect(0, 0, 210, 10, 'F')
        
        self.set_font('helvetica', 'B', 15)
        self.set_text_color(255, 255, 255)
        self.cell(0, 5, 'Datavise AI - Analytical Report', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(160, 160, 160)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Datavise AI on {datetime.now().strftime("%Y-%m-%d")}', 0, 0, 'C')

def generate_session_pdf(session_id: str, messages: list[dict]) -> bytes:
    """Compiles session chat history and charts into a PDF."""
    pdf = AnalysisReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # 1. Get Session Info
    session = data_loader.get_session(session_id)
    if not session:
        return b""
    
    df = session["df"]
    profile = session["profile"]

    # 2. Executive Summary
    pdf.set_font('helvetica', 'B', 16)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 10, "Executive Data Summary", 0, 1)
    pdf.ln(2)

    pdf.set_font('helvetica', '', 11)
    pdf.multi_cell(0, 7, f"This report contains an automated analysis of the uploaded dataset. The dataset contains {len(df)} records across {len(df.columns)} dimensions.")
    pdf.ln(5)

    # 3. Iterate through Chat History
    # Filter only pairs of (User Question -> Assistant Insight)
    q_and_a = []
    current_q = None
    for msg in messages:
        if msg["role"] == "user":
            current_q = msg["content"]
        elif msg["role"] == "assistant" and current_q:
            q_and_a.append((current_q, msg["content"]))
            current_q = None

    for idx, (question, insight) in enumerate(q_and_a):
        # Section Header
        pdf.set_font('helvetica', 'B', 12)
        pdf.set_text_color(251, 113, 133)
        pdf.cell(0, 10, f"Analysis {idx+1}: {question}", 0, 1)
        pdf.ln(1)

        # Insight Text
        pdf.set_font('helvetica', '', 10)
        pdf.set_text_color(50, 50, 50)
        pdf.multi_cell(0, 6, insight)
        pdf.ln(5)

        # Attempt to re-run only the visualization for this question (simplified logic)
        # In a real app, we'd store the final_code or chart_json in DB.
        # For now, let's try a heuristic export or just skip if we don't have code.
        # NOTE: To be robust, we'll assume we can't re-run code easily here without risk.
        # Instead, we'll mostly focus on the "Aesthetic" layout of the text and tables.
        
        if pdf.get_y() > 250: pdf.add_page()

    # 4. Data Preview Table
    pdf.add_page()
    pdf.set_font('helvetica', 'B', 14)
    pdf.set_text_color(30,30,30)
    pdf.cell(0, 10, "Raw Data Snapshot (Top 10)", 0, 1)
    pdf.ln(2)

    # Simple table implementation
    pdf.set_font('helvetica', 'B', 8)
    cols = df.columns[:7] # Limit columns for fit
    col_width = 190 / len(cols)
    
    for col in cols:
        pdf.cell(col_width, 8, str(col)[:15], 1)
    pdf.ln()

    pdf.set_font('helvetica', '', 7)
    for i in range(min(len(df), 10)):
        for col in cols:
            pdf.cell(col_width, 6, str(df.iloc[i][col])[:20], 1)
        pdf.ln()

    return bytes(pdf.output())